exports.seed = function(knex) {
  // Deletes ALL existing entries
  return knex('candidates').del()
    .then(function () {
      // Inserts seed entries
      return knex('candidates').insert(
        // عمان اولى
        [{
          
    name: "أماني محمد",
    city: "الزرقاء",
    list: "قائمة بناة الوطن",
    circle: "الدائرة الثالثة",
    party: "حزب إرادة",
    circle_list: "قائمة الدائرة الثالثة",
    candidate_votes: 0,
    list_votes: 0,
    gender: "female",
    type: "كوتا",
    isActivate: true,
    party_votes : 0 ,
    candidate_national_id: 197547 ,
  } ,
{
    name: "اسامة عمر",
    city: "الزرقاء",
    list: "قائمة بناة الوطن",
    circle: "الدائرة الثالثة",
    party: "حزب إرادة",
    circle_list: "قائمة الدائرة الثالثة",
    candidate_votes: 0,
    list_votes: 0,
    gender: "male",
    type: "مسيحي",
    isActivate: true,
    party_votes : 0 ,
    candidate_national_id: 1559017 ,
  } ,
{
    name: "كمال صالح",
    city: "الزرقاء",
    list: "قائمة بناة الوطن",
    circle: "الدائرة الثالثة",
    party: "حزب إرادة",
    circle_list: "قائمة الدائرة الثالثة",
    candidate_votes: 0,
    list_votes: 0,
    gender: "male",
    type: "شركسي",
    isActivate: true,    party_votes : 0 ,
    candidate_national_id: 400017 ,
  } ,
{
    name: "نور الدين فادي",
    city: "الزرقاء",
    list: "قائمة بناة الوطن",
    circle: "الدائرة الثالثة",
    party: "حزب إرادة",
    circle_list: "قائمة الدائرة الثالثة",
    candidate_votes: 0,
    list_votes: 0,
    gender: "male",
    type: "مسلم",
    isActivate: true,
    party_votes : 0 ,
    candidate_national_id: 473217 ,
  } ,

{
    name: "صلاح مطاوع",
    city: "الزرقاء",
    list: "قائمة بناة الوطن",
    circle: "الدائرة الثالثة",
    party: "حزب إرادة",
    circle_list: "قائمة الدائرة الثالثة",
    candidate_votes: 0,
    list_votes: 0,
    gender: "male",
    type: "مسلم",
    isActivate: true,
    party_votes : 0 ,
    candidate_national_id: 259367 ,
  } ,

{
    name: "عيد عطا الله",
    city: "الزرقاء",
    list: "قائمة بناة الوطن",
    circle: "الدائرة الثالثة",
    party: "حزب إرادة",
    circle_list: "قائمة الدائرة الثالثة",
    candidate_votes: 0,
    list_votes: 0,
    gender: "male",
    type: "مسلم",
    isActivate: true,
    party_votes : 0 ,
    candidate_national_id: 2589217 ,
  } ,

{
    name: "سمر هاني",
    city: "الزرقاء",
    list: "قائمة بناة الوطن",
    circle: "الدائرة الثالثة",
    party: "حزب إرادة",
    circle_list: "قائمة الدائرة الثالثة",
    candidate_votes: 0,
    list_votes: 0,
    gender: "female",
    type: "مسلم",
    isActivate: true,
    party_votes : 0 ,
    candidate_national_id: 189017 ,
  } ,

{
    name: "رافع محمود",
    city: "الزرقاء",
    list: "قائمة بناة الوطن",
    circle: "الدائرة الثالثة",
    party: "حزب إرادة",
    circle_list: "قائمة الدائرة الثالثة",
    candidate_votes: 0,
    list_votes: 0,
    gender: "male",
    type: "مسلم",
    isActivate: true,
    party_votes : 0 ,
    candidate_national_id: 679017 ,
  } ,

{
    name: "صخر سميح",
    city: "الزرقاء",
    list: "قائمة بناة الوطن",
    circle: "الدائرة الثالثة",
    party: "حزب إرادة",
    circle_list: "قائمة الدائرة الثالثة",
    candidate_votes: 0,
    list_votes: 0,
    gender: "male",
    type: "مسلم",
    isActivate: true,
    party_votes : 0 ,
    candidate_national_id: 579443 ,
  } ,

{
    name: "مهند فاتح",
    city: "الزرقاء",
    list: "قائمة بناة الوطن",
    circle: "الدائرة الثالثة",
    party: "حزب إرادة",
    circle_list: "قائمة الدائرة الثالثة",
    candidate_votes: 0,
    list_votes: 0,
    gender: "male",
    type: "مسلم",
    isActivate: true,
    party_votes : 0 ,
    candidate_national_id: 759117 ,
  } 
]
        );
    });
};


